### ISSUE TITLE
[FR] import more sheets objects (chart to table)

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel#100]
At the moment you can only Qlik Sense tables import. Is it possible to import a chart as an table?
So the user can be import charts also like an table.

**Comment by konne** [comment]
yes, this is an interesting point, but be honest, the user expects that he see the real "same" chart in Excel
This is in some parts possible, but not easy.
The next step on top would be than, to import a complete sheet from sense with than multipe charts,..
