### ISSUE TITLE
[BUG] lost SenseEV functionality when duplicate the current sheet to a new sheet

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel#102]
![image](https://user-images.githubusercontent.com/13659581/52277004-f28f1b00-2953-11e9-93c6-ce4c1a9a51f1.png)

![image](https://user-images.githubusercontent.com/13659581/52277021-0044a080-2954-11e9-8d59-5f7ddfdb9f20.png)

**Comment by konne** [comment]
@AlexanderGoerlich please check again with the new Version (tomorrow from @ChristofHoldschick), in the devBranch, it is complete working

**Comment by thomashaenig** [comment]
is fixed, will be closed
