### ISSUE TITLE
[BUG] - disable buttons if there is no connection to a HUB

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel#104]
![image](https://user-images.githubusercontent.com/13659581/52630037-646ae580-2ebb-11e9-8dcf-6cc3434b6109.png)

It confuses the user and associates the user can click.

**Comment by ChristofHoldschick** [comment]
When does thid happen?

**Comment by AlexanderGoerlich** [comment]
when I open a new Excel File!
