### ISSUE TITLE
[BUG] support tables greater than 1.000.000 lines 

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel#105]
Want we support that?

**Comment by ChristofHoldschick** [comment]
(greater than 1048576 lines )
worksheet.Cells can't take bigger numbers

**Comment by konne** [comment]
👍 yes with Backend Data for Pivot Tables or Charts

**Comment by AlexanderGoerlich** [comment]
Feature | Maximum limit
-- | --
Open workbooks | Limited by available memory and system resources
Total number of rows and columns on a worksheet | 1,048,576 rows by 16,384 columns
Column width | 255 characters
Row height | 409 points
Page breaks | 1,026 horizontal and vertical
Total number of characters that a cell can contain | 32,767 characters
Characters in a header or footer | 255
Maximum number of line feeds per cell | 253
Sheets in a workbook | Limited by available memory (default is 1 sheet)
Colors in a workbook | 16 million colors (32 bit with full access to 24 bit color spectrum)
Named views in a workbook | Limited by available memory
Unique cell formats/cell styles | 64,000
Fill styles | 256
Line weight and styles | 256
Unique font types | 1,024 global fonts available for use; 512 per workbook
Number formats in a workbook | Between 200 and 250, depending on the language version of Excel that you have installed
Names in a workbook | Limited by available memory
Windows in a workbook | Limited by available memory
Hyperlinks in a worksheet | 66,530 hyperlinks
Panes in a window | 4
Linked sheets | Limited by available memory
Scenarios | Limited by available memory; a summary report shows only the first 251 scenarios
Changing cells in a scenario | 32
Adjustable cells in Solver | 200
Custom functions | Limited by available memory
Zoom range | 10 percent to 400 percent
Reports | Limited by available memory
Sort references | 64 in a single sort; unlimited when using sequential sorts
Undo levels | 100
Fields in a data form | 32
Workbook parameters | 255 parameters per workbook
Items displayed in filter drop-down lists | 10,000
Noncontiguous cells that can be selected | 2,147,483,648 cells
Maximum limits of memory storage and file size for Data Model workbooks | 32-bit environment is subject to 2 gigabytes (GB) of virtual address space, shared by Excel, the workbook, and add-ins that run in the same process. A data model’s share of the address space might run up to 500 – 700 megabytes (MB), but could be less if other data models and add-ins are loaded.64-bit environment imposes no hard limits on file size. Workbook size is limited only by available memory and system resources.Excel 2016 offers the Large Address Aware functionality that lets 32-bit Excel 2016 consume twice the memory when users work on a 64-bit Windows operating system. For more information, see Large Address Aware capability change for Excel.Note: Adding tables to the Data Model increases the file size. If you don’t plan to create complex Data Model relationships using many data sources and data types in your workbook, uncheck the Add this data to the Data Model box when you import or create tables, pivot tables, or data connections.For more information, see Data Model specification and limits.
Processor Cores | 64

**Comment by AlexanderGoerlich** [comment]
wont fix: #107
