### ISSUE TITLE
[FR] Ability to tag certain master 

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel#113]
Ability to tag certain master items so that only these are shown within Sense Excel?

This is a new idea - but in the applications, we have many fields and not all will be appropriate to be shown within Sense Excel.

Would it be possible at some stage to use the tags property of a master item to restrict those that are shown in Sense Excel?

@konne : we have to discuss!

**Comment by thomashaenig** [comment]
check if can be closed
