### ISSUE TITLE
SenseFilter is ignored on re-connect.

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel#117]
When SenseExcel connects to the app, all rows are fetched, ignoring existing SenseFilter () constraints.

Example:

1. I open an Excel file that already has a SenseExcel spreadsheet restricted by SenseFilter ().

2. When connecting to the app, all the app's records are first loaded with respect to the dimensions of the SenseExcel table, i. the SenseFilter () is ignored.

3. The result can be extremely long waiting times or even Excel crashes (imagine a table with 100 million rows of data, of which by means of filters but actually only 10 pieces are to be called).

Workaround:

If Excel is calculating formulas and the options is set to "manual", the loading is initially suppressed. 
When you connect to the app, nothing happens first, that´s good. Now, the SenseFilters () can be applied manually via F2 + Enter.
So, if I set the formula calculation in Excel back to automatic, it updates the table according to the pre-filtering already selected.

Accordingly, this can be done in a few seconds. Without this workaround, Excel will crash or take several hours for larger, original datasets.

**Comment by thomashaenig** [comment]
possible solution, should be discussed, first check for SenseFilter, execute them and then make the senseEV and Table calculation
