### ISSUE TITLE
[BUG] optimize for compatibility glitch

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel#128]
Workaround: Change the Excel display setting (see attached Image) to "Optimize for compatibility" and restart Excel.

Actually, the sections “Sorteren” and “Uitbreidingsmodules” are not visible on the first screen.  Sometimes I can see the beginnings of these sections on the first screen:
![image](https://user-images.githubusercontent.com/13659581/53019754-baa8cd00-3455-11e9-90f4-17d9db32ef92.png)

**Comment by thomashaenig** [comment]
needs to be checked
recreate: two monitors one with increased view scalling, when switching between monitors, shows wrong views

**Comment by thomashaenig** [comment]
error ocured only in old desiges, so with the redesign of AG Excel Plugin the issues is fixed
