### ISSUE TITLE
Fast Add Dialogue Box

### ISSUE THREAD

**Issue by harrislance** [senseexcel/senseexcel#15]
When using the Fast Add box, the bottom of the dialogue box and action buttons stay hidden below the Windows taskbar.  The bottom of the box can't be moved or resized to make the buttons visible.

**Comment by konne** [comment]
@ChristofHoldschick please check this

**Comment by ChristofHoldschick** [comment]
From Lance Harris per Mail:
As you can see the OK and Cancel buttons in the fast add dialogue box are still hidden under the Taskbar. 
I am using the 3.1.2-64 version.
![screenshot](https://user-images.githubusercontent.com/35026589/44380060-702baf80-a509-11e8-813a-7b7ec7f17855.png)

**Comment by ChristofHoldschick** [comment]
I could reproduce the problem, with 2 monitors. One set to a high Resolution (2560x1440), and on the other monitor, set a magnification >100%.
...solved the issue for this Environment.
