### ISSUE TITLE
Numbers 2,019 is converted to 2.019 when passed to Excel

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel#156]
When in Qlik a Dimension is numeric and has 3 (or a multiple of 3) diggits after the comma Excel turns  comma as a point, which  is a thousand seperator. 
if there are less than 3 diggits after the comma Excel take the Number as a string.
So this Number 2,019 will turn to 2.019 but Number 0,34 will still be 0,34

**Comment by thomashaenig** [comment]
is fixed, will be closed
