### ISSUE TITLE
Sense Table Formatting Issue

### ISSUE THREAD

**Issue by harrislance** [senseexcel/senseexcel#16]
When using the Qlik Sense Table property panel, changes to "Number Format" do not effect the Excel table either before or after pressing the "check" box.

**Comment by konne** [comment]
@ChristofHoldschick this is realated to our discussion about the format transfer into Excel

**Comment by AlexanderGoerlich** [comment]
Sense Excel only gives a plain data formatting this can you fix directly on the excel side!
