### ISSUE TITLE
New Support Process: Emails

### ISSUE THREAD

**Issue by konne** [senseexcel/senseexcel#17]
all new support emails have to be sent to:

LASTREQUESTESSERIAL@senseexcel.com

save this always to the config.json, so that is also available direct after the start

or if the system never could connect and fetch a license from the QMC, ask for the serial in a dialog.

**Comment by ChristofHoldschick** [comment]
Zip the Logfile before attaching it to the Support-Mail. Because of the SizeLimitations of outgoing Emails

**Comment by ChristofHoldschick** [comment]
if a Connection is successfully established, the serieal is saved in the sense-excel.jsconfig under the 'LastRequestSerial' Entry.
```json
{
  "Language": "en-US",
  "SelectionPane": true,
  "LastRequestSerial": "123456789012345",
  "FirstStart": true,
  "..."
```
 If the User opens a supportmail, *serialnumber* at senseexcel.com is used. If this Entry is not set and the SupportMail is generated, a Messagebox appears, wich asks for the serial. if no Serial is entered or the User selects Cancel, the fallback address  qvm_support at qlik2go.net is used.
![sierialinputbox](https://user-images.githubusercontent.com/35026589/47152488-25e26700-d2dd-11e8-9e94-7f616655cc58.png)

The attached logfile is zipped and the created zip-file is stored in %AppData%\Roaming\akquinet\SenseExcel\logs\senseexcel_attached-log_*Timestamp*.zip
these Files can be savely deleted, after the supportmail is sent.

If SenseExcel is installed, the serial number should be entered in the 'LastRequestSerial' entry of the sense-excel.jsconfig, or a first connect to a server should be executed, so the user never has to enter the serial manually in the inputdialog.
