### ISSUE TITLE
Slow Refresh v 3.1.2

### ISSUE THREAD

**Issue by harrislance** [senseexcel/senseexcel#24]
When updating a complex report in version 3.1.2 the update/calculation process is very slow - much like 2.x versions before multi-threading.  

When same report is opened in 3.1.0 the open/calc process is much faster.

**Comment by ChristofHoldschick** [comment]
Hi Lance,
can you describe what complex meams, so we can recontruct the Problem? (what elements are contained and how many eg. Tables, SenseEV-formulas) 
or could you attach app and xlsx?
Is "Updating" changing a Filter/applying a Bookmark?

**Comment by harrislance** [comment]
See attached.

The issue is the initial calculation upon open/initial app connect.

**Comment by ChristofHoldschick** [comment]
Hi Lance,
sorry, but can you attach the files directly to the github issue. It seems that Email attachments are ignored by github.

**Comment by ChristofHoldschick** [comment]
@harrislance could you please add the Files directly to the Github Issue, as the Mailattachment is ignored by Github
