### ISSUE TITLE
[FR] - Save current .xlsx view without SenseEV values

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel#25]
A way to save- or export button directly from Sense Excel!  
Export or save the current output data (there should be no "Sense EV" formulas ... only the numerical values from the EV)!

Thus, the *.xlsx file can be opened without SE! 
So that export/save option... creates a new * .xlsx file how can be made available to someone. 
(analogous to report)

**Comment by thomashaenig** [comment]
is done by reporting, check if can be closed

**Comment by thomashaenig** [comment]
moved to new repo
