### ISSUE TITLE
[FR] Metadatacheck

### ISSUE THREAD

**Issue by konne** [senseexcel/senseexcel#28]
store into the xlsx the metadata of the qlik app like
  * Dimensions
  * Measures
  * Fields
If you reconnect to the app and the metadata are different to the current
metadata there is a Warning / Info in the Ribbon. If you click on that
you get a list of changes. For example: 2 fields added (FieldA, FieldB)
1 field removed,...

**Comment by thomashaenig** [comment]
moved to new repo
