### ISSUE TITLE
[FR] Two Table Creation Options or Allow Users Choice

### ISSUE THREAD

**Issue by harrislance** [senseexcel/senseexcel#3]
Is there any consideration of including the old Create Table approach in the new versions of SE 3?  

Although the new Table Property Panel is very elegant and does look and feel just like Qlik Sense it requires a number of additional steps, like having to choose Dimension, Measure of Formula for each column and not being able to multi select.  

Could we have an additional button for “Quick Table” that would execute the old approach in addition to “Table” option that uses the new Table Property Panel? 

Could we have it as a Setting that could be chosen by the user?  Create Table Setting :  Quick vs. Complete (or similar)?

**Comment by konne** [comment]
A new functionality is added to the Property Panel "Fast Add"

@harrislance please document before we close that issue
