### ISSUE TITLE
Apps in Streams Don't Always Show Up

### ISSUE THREAD

**Issue by harrislance** [senseexcel/senseexcel#30]
Version 3.0.7 3.0.9. 3.0.10 3.1.0 3.1.2  All 64 bit

When logging into Sense Excel via okta single sign on, Apps in Streams only show up part of the time.  When they do appear, the user can click on a given app but the table button never appears.  In the same workflow, the app will crash and not reload even though the auto-load check has been activated.

**Comment by ChristofHoldschick** [comment]
One of the two Problems (Apps dont show ) is treated by #37
