### ISSUE TITLE
[FR] - Show current opened app

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel#32]
When open an app show the app cube with picture and name like the HUB

**Comment by ChristofHoldschick** [comment]
The App-Icon and Name are shown next to the Hub-Icon, if an app is loaded

**Comment by ChristofHoldschick** [comment]
moved the app icon in the selection bar
like so:
![grafik](https://user-images.githubusercontent.com/35026589/47958982-fa979180-dfd7-11e8-82be-a2c71ccad71f.png)
