### ISSUE TITLE
Check/Vaidation for apps

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel#50]
Check for things like, Table's Dimension/Measures belongs to different app, missconfiguration not visible to the user, to reduce support requests. Like the Connections-check.

- [x] A
- [x] B
- [ ] C

**Comment by thomashaenig** [comment]
reference to #28;
maybe display hint the table belongs not to the app, or field in this app not found

**Comment by thomashaenig** [comment]
moved to new repo
