### ISSUE TITLE
Extend Scripteditor for C# SER-Scripts

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel#53]
In SER one can start c# scripts.
Extend the Scripteditor to support editing (syntaxhighlighting).
Also find a way to start the code-signing from the editor.
@konne @AlexanderGoerlich  please evaluate...

**Comment by ChristofHoldschick** [comment]
@mossbeard FYI

**Comment by konne** [comment]
that make sense, this should be embedded in general into the config for the report tasks

**Comment by thomashaenig** [comment]
check with customer if required

**Comment by thomashaenig** [comment]
moved to new repo
