### ISSUE TITLE
[FR] - Alternate State Support

### ISSUE THREAD

**Issue by konne** [senseexcel/senseexcel#55]
please add support after q2g/daVinci-wpf#39 is implemented

**Comment by konne** [comment]
@AlexanderGoerlich please add milestone

**Comment by ChristofHoldschick** [comment]
Support multiple selections with diferent alternate states like in QLIK:
![grafik](https://user-images.githubusercontent.com/35026589/49436498-91af5f00-f7b9-11e8-8b58-6d552159aa85.png)

New alternate states can be created in the selection tool window.
it should be possible to switch between states and view selections of different states.

Tableeditor should be enhanced to assign alternate states to tables
