### ISSUE TITLE
[Bug] Fieldname is empty in tableeditor after import

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel#62]
When importing a table with a field column, the label is empty, 
Qlik in this case takes the Formula as fallback for the label. 
 
In Qlik
![grafik](https://user-images.githubusercontent.com/35026589/47906945-8f8c7480-de8a-11e8-8ce4-0ca98c592247.png)

In Sense Excel
![grafik](https://user-images.githubusercontent.com/35026589/47906922-83081c00-de8a-11e8-9cf0-df5c0ea8a137.png)

Formula should be taken as fallback in sense excel.

**Comment by konne** [comment]
@AlexanderGoerlich please confirm, for me that is okay, this is a very small change

**Comment by konne** [comment]
@AlexanderGoerlich please add Milestone
