### ISSUE TITLE
Download Versions

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel#67]
On update.senseexcel.com all Versions are available as zip-files and can be accessed via directory listing
a Zip file contains:
* xll 32bit
* xll 64 bit
* releasenotes for the above xlls

In the Qlik desktop client, every version can be used.
in Qlik server environment, a limitation can be set in the license.txt.
With the new Key 'senseexcel_versions' the limitations could be set in the following format:
 senseexcel_versions;YES;<version_from>;<version_to>;<specific_version>;<specific_version>;...
* version_from: allow all Versions newer than this version, this version included; if empty: allow all version from the beginning of all times on
* version_to: allow all versions older than this version , this version included; if empty: allow all new versions
* specific_version: additional to version_from, version_to allow this version

Example: ```senseexcel_versions;YES;3.0.1;3.3.0;4.0.0-beta1;4.0.0-beta2 ```
This will allow all Version from (and including) 3.0.1 to (and including) 3.3.0 but additionally allows the versions 4.0.0-beta1 and 4.0.0-beta2.

If Sense Excel connects to a server, it downloads the license.txt and extracts all allowed versions from the license.txt. It takes the serial of the license and adds a folder named by this serial in the %appdata%\senseexcel\versions\ directory.
In this directory it saves a versions.txt wich contains all allowed versions for this server. The versions-Directory is later consumed by the xll-loader, so it can display, to wich version the user can switch depending an which server the user wants to connect.
Later if the user decides to switch to a version, zhe xll-loader downloads it to %appdata%\senseexcel\versions\versioncache\ directory. So all versions are only downloaded once.

This results in the following directory:
*  %appdata%\senseexcel\versions
    * versioncache
      * senseexcel3.0.1.zip
      * senseexcel3.2.0.zip
      * senseexcel3.3.0.zip
      * senseexcel4.0.0-beta1.zip
      * senseexcel4.0.0-beta2.zip 
    * 12345678
      * versions.txt
    * 09876543
      * versions.txt

Where 12345678 and 09876543 are two servers, with the serial as foldername.

if, for exapmle, the server with the id 12345678 is the live(production) server, it's license.txt contains the line:   ```senseexcel_versions;YES;3.0.1;3.3.0; ```
and if the server with the id 09876543 is the test server, it's license.txt contains the line:   ```senseexcel_versions;YES;3.0.1;3.3.0;4.0.0-beta1;4.0.0-beta2 ```

**Comment by ChristofHoldschick** [comment]
@konne, @AlexanderGoerlich  please consider.

**Comment by konne** [comment]
@ChristofHoldschick for the LEF extension:

EXCEL_VERSION;3.2;BEGIN;ENDDATE  // Version 3.2
EXCEL_VERSION;3.3;BEGIN;ENDDATE // Version 3.3
EXCEL_VERSION;2.*;;;      // all Version from 2. relase
EXCEL_VERSION;*-beta;;  // all with BETA Flag

The Directory is fine for me

@AlexanderGoerlich  please give your feedback
