### ISSUE TITLE
Table: Fontcolor is taken as backcolor 

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel#70]
In a table, if one set a Font color for a measure, and no backcolor, the fontcolor is taken as backcolor
If a Backcolor AND a Fontcolor is configured, all works fine.

So for a Workaround, set Fontcolor to the color you like and backcolor to White (or any other color)

**Comment by konne** [comment]
@ChristofHoldschick is this a problem only in SE or also in SER
