### ISSUE TITLE
Dont Clear Format, when refreshing table, just remove color

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel#73]
Problem:
ATM. the Excel-Format of a table is removed when changing a table.
When the user inserted a Table and set the columnformat in Excel, it wil be cleared out, when the Table is refreshed by clicking the green tick in the property panel or selecting refresh in the context menu.

Expected:
The Excelformat should not be deleted after a table refresh 

@konne @AlexanderGoerlich , please evaluate.

**Comment by AlexanderGoerlich** [comment]
Notice: when shema color is changed to dark:

![image](https://user-images.githubusercontent.com/13659581/48936734-170a5800-ef0c-11e8-9fb1-68ae69fb721d.png)

**Comment by thomashaenig** [comment]
is fixed, will be closed
