### ISSUE TITLE
Table: remove old tabledata if table has errors

### ISSUE THREAD

**Issue by ChristofHoldschick** [senseexcel/senseexcel#75]
Problem:
if the user edits a table and maks an error (e.g. enters wrong name of a field) the table isnt cleared out.
So the user see the old data of the table before the edit.
if he dont notice it, he edits on a errorunos table and gets no feedbck that something went wrong...

Solution:
clear the table on errors

**Comment by ChristofHoldschick** [comment]
column wich causes the error should get '-' as values

**Comment by ChristofHoldschick** [comment]
Doesn't work for pivot-tables. If a Field/Dimension is corrupt, it will be ignored by qlik. And the first Column-Dimension becomes a Row Dimension.

**Comment by AlexanderGoerlich** [comment]
please can you check that in Qlik
