### ISSUE TITLE
no values shown in excel spreadsheet after 3.2.1 update

### ISSUE THREAD

**Issue by Exceltante** [senseexcel/senseexcel#86]
![se bug](https://user-images.githubusercontent.com/40390537/49861845-1d9a3a00-fdfd-11e8-9a87-4dfd8d77dad3.GIF)

After changing the Add In to Sense Excel 3.2.1. there are no values shown in the excel spreadsheet while the HUB is correctly connected

**Comment by ChristofHoldschick** [comment]
Did you restart excel after updating to the 3.2.1 Version?
everything is Working for me...

* I opened A Document (ExcecutiveDashboard_SenseExce.xlsx) with 3.2.0 
* SenseEV get calculated
* Then opended this document with 3.2.1 
* All SenseEv's are also filled fine.

Maybe you can attach app and document to this issue, so I can have a look if I can reproduce this behavior.

Please be aware, that this Git-Project is public so everyone can read the issues created here, so never attach sensible data. (only add demo data).

**Comment by konne** [comment]
@Exceltante @ChristofHoldschick this is the #NV issue. ONE Time you have to make a replace (Strg+H) and replace just senseev with senseev. After that everything should work. After you have saved the file this never appears again.
@AlexanderGoerlich please document this in FAQ
