### ISSUE TITLE
sheetloop

### ISSUE THREAD

**Issue by konne** [senseexcel/senseexcel#88]
not as extra entry in the submenu.

![image](https://user-images.githubusercontent.com/1100969/50047122-bd7eee80-00af-11e9-8f60-105285bf23ff.png)

This need to be in the edit sheet loop dialog. Also it need to be visible if this sheet has an sheetloop.
Onces in the Dialog but also extra in the submenu for example with an selected icon
![image](https://user-images.githubusercontent.com/1100969/50047134-e1dacb00-00af-11e9-8526-76a3009e16db.png)

**Comment by ChristofHoldschick** [comment]
If the user inserts data, which is not represented by the dialog, all controls should be disabled(grayed). 

If sheetname is not set, the checkbox chuld be unchecked and vice versa.
![grafik](https://user-images.githubusercontent.com/35026589/51389253-ffc2a200-1b2b-11e9-83c5-26cb2c7b03d0.png)
