### ISSUE TITLE
[BUG] Alternate State in Selectionbar

### ISSUE THREAD

**Issue by konne** [senseexcel/senseexcel#90]
the state should be only visible if the APP Contains MORE than one State. Like Qlik Sense Nov Release

![image](https://user-images.githubusercontent.com/1100969/50345170-62754d80-052e-11e9-8f5d-62ebadf89604.png)

**Comment by ChristofHoldschick** [comment]
fixed in https://github.com/q2g/daVinci-wpf/pull/67
