### ISSUE TITLE
[BUG] Bookmark Delete Dialog not centered

### ISSUE THREAD

**Issue by konne** [senseexcel/senseexcel#91]
see picture:

![image](https://user-images.githubusercontent.com/1100969/50358737-9fefd000-055a-11e9-83ae-dd83a91b1021.png)

**Comment by konne** [comment]
extra you have to confirm double the delete, the second Dialog than is centered

![image](https://user-images.githubusercontent.com/1100969/50358813-e47b6b80-055a-11e9-8eda-f21931ab1a31.png)

**Comment by ChristofHoldschick** [comment]
Solved in https://github.com/q2g/se-xll/pull/83
