### ISSUE TITLE
[BUG] Alternate State after App Change

### ISSUE THREAD

**Issue by konne** [senseexcel/senseexcel#93]
Steps to reproduce:

1. Open Executive Dashboard
2. make a Selection in State "test2"
3. change App to HelpDesk (contains not test2 state, only test1 state)
you get following picture:

![image](https://user-images.githubusercontent.com/1100969/50359098-c9f5c200-055b-11e9-88fa-c1217bbe6d17.png)

**Comment by ChristofHoldschick** [comment]
fixed in https://github.com/q2g/q2g-helper-sense-nuget/pull/16
